### ISSUE TITLE
后端json类型数据前端无法读取

### ISSUE THREAD

**Issue by 2039358295** [Helianthus-259/Digital_Hundred_Clubs#1]
前端写入json数据，后端存入数据库为json格式；
后端读出json给前端时，前端没法解析json数据
`@Override
    public Object queryClubIntroductionByClubId(Integer clubId) {
        MPJLambdaWrapper<Club> wrapper = new MPJLambdaWrapper<Club>()
                .selectAll(Club.class)
                .eq(Club::getClubId,clubId);
        try {
            Object clubDescription = clubMapper.selectOne(wrapper, true).getClubDescription();
            return Result.success(new ClubDescriptionVO(ResultCode.GET_CLUB_INTRODUCTION,clubDescription));
        } catch (Exception e) {
            String exceptionAsString = e.toString();
            return Result.send(StatusCode.GET_CLUB_INTRODUCTION_ERROR,new SendMsg(exceptionAsString));
        }
    }`

**Comment by MoonHingyee** [comment]
加入MyJsonParser类后修复，对所有数据库json数据进行处理后传送给前端
