### ISSUE TITLE
富文本图片显示出错

### ISSUE THREAD

**Issue by MoonHingyee** [Helianthus-259/Digital_Hundred_Clubs#2]
富文本需要插入图片并显示，但图片上传的逻辑为上传后返回相对路径而不是url，而富文本作为text存储在数据库中无法解析其中的相对地址转换为url。
`file.transferTo(dest);
            // 获取文件的规范路径
            String absolutePath = dest.getCanonicalPath();
            System.out.println(absolutePath);
            // 获取相对路径
            String relativePath = absolutePath.substring(baseRoot.length());
            // 返回相对路径
            // 创建一个HashMap
            HashMap<String, Object> dataMap = new HashMap<>();
            dataMap.put("code", ResultCode.UPLOAD_IMAGE.getCode());
            dataMap.put("image", new FileVO(relativePath,flag));
            return Result.success(dataMap);
        } catch (IllegalStateException | IOException e) {
            e.printStackTrace();
            Result.send(StatusCode.UPLOAD_IMAGE_ERROR,new SendMsg("上传图片失败"));
        }`

**Comment by 2039358295** [comment]
在后端处理时对富文本上传图片区别对待，直接返回url供富文本存储图片url地址显示：
`if(flag.equals("editor")){
                relativePath = FileRequestUrlBuilder.buildFileRequestUrl(relativePath);
                dataMap.put("image", new FileVO(relativePath,flag));
            }else{
                dataMap.put("image", new FileVO(relativePath,flag));
            }`
